- name: Playbook to install common tools
  hosts: all
  remote_user: ubuntu
  tasks:
  - name: Install unzip
    apt:
        update_cache: yes
        name: unzip
        state: latest
  - name: Install curl
    apt:
      name: curl
      state: latest
  - name: Install wget
    apt:
      name: wget
      state: latest
  - name: Install JAVA
    apt:
        name: openjdk-11-jdk
        state: present 
  - name: Set the JAVA_HOME in /etc/profile file
    lineinfile:
        path: /etc/profile
        state: present
        line: "{{ item }}"
    with_items:
        - 'export JAVA_HOME="/usr/lib/jvm/java-11-openjdk-amd64"'
        - 'export PATH=$PATH:$JAVA_HOME/bin'
  - name: Reload /etc/profile file
    shell:
      cmd: . /etc/profile
  - name: set timezone
    shell:
      cmd: timedatectl set-timezone America/Bogota